# Generated by Django 5.1.4 on 2024-12-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("stock_number", models.CharField(max_length=10)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ONS", "ONS"), ("SLD", "SLD")], max_length=3
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("USED", "USED"), ("NEW", "NEW")], max_length=4
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("photos_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("ABC", "ABC"), ("XYZ", "XYZ"), ("QWE", "QWE")],
                        max_length=3,
                    ),
                ),
                ("vdp", models.IntegerField()),
                ("srp", models.IntegerField()),
                (
                    "vin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="api.vehicle",
                        to_field="vin",
                    ),
                ),
            ],
        ),
    ]
