# Generated by Django 5.1.4 on 2024-12-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_vehicle_description_alter_vehicle_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="source",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(max_length=4),
        ),
    ]
